### ISSUE TITLE
Package.json errors

### ISSUE THREAD

**Issue by Ayush4385** [Leref/DBD.js#6]
@Leref the package.json present in this repo or that in server shows many errors!I cant run my bot please help

**Comment by LachlanDev** [comment]
What's the error message?

**Comment by theayushkumar** [comment]
@LachlanDev there are different errors in different compilers

**Comment by LatoSato** [comment]
yeah it might be outdated
best to just install dbd.js through npm or make your own package.json

In fact if you install through package.json, you cant rly publish it to npm, sooo yeah
